scoreFile=$1;
defFile=$2;
#cp ~/Downloads/tmp/*.json .
sed -i bak -e s/match_scores/matchScores/g $scoreFile
sed -i bak -e s/stage_stagescores/stageStagescores/g $scoreFile
sed -i bak -e s/stage_number/stageNumber/g $scoreFile
sed -i bak -e s/stage_uuid/stageUuid/g $scoreFile
sed -i bak -e s/match_id/matchId/g $scoreFile

sed -i bak -e s/match_id/matchId/g $defFile
sed -i bak -e s/match_type/matchType/g $defFile
sed -i bak -e s/match_date/matchDate/g $defFile
sed -i bak -e s/match_cats/matchCats/g $defFile
sed -i bak -e s/match_approvescores/matchApprovescores/g $defFile
sed -i bak -e s/match_name/matchName/g $defFile
sed -i bak -e s/match_readonly/matchReadonly/g $defFile
sed -i bak -e s/match_bonuses/matchBonuses/g $defFile
sed -i bak -e s/match_penalties/matchPenalties/g $defFile
sed -i bak -e s/pen_val/penVal/g $defFile
sed -i bak -e s/pen_bin/penBin/g $defFile
sed -i bak -e s/pen_name/penName/g $defFile
sed -i bak -e s/match_cls/matchCls/g $defFile
sed -i bak -e s/match_logenabled/matchLogenabled/g $defFile
sed -i bak -e s/match_stages/matchStages/g $defFile
sed -i bak -e s/match_modifieddate/matchModifieddate/g $defFile
sed -i bak -e s/match_shooters/matchShooters/g $defFile
sed -i bak -e s/match_creationdate/matchCreationdate/g $defFile
sed -i bak -e s/match_owner/matchOwner/g $defFile
sed -i bak -e s/stage_poppers/stagePoppers/g $defFile
sed -i bak -e s/stage_number/stageNumber/g $defFile
sed -i bak -e s/stage_uuid/stageUuid/g $defFile
sed -i bak -e s/stage_targets/stageTargets/g $defFile
sed -i bak -e s/stage_name/stageName/g $defFile
sed -i bak -e s/stage_classifier/stageClassifier/g $defFile
sed -i bak -e s/stage_scoretype/stageScoretype/g $defFile
sed -i bak -e s/stage_modifieddate/stageModifieddate/g $defFile
sed -i bak -e s/stage_classifiercode/stageClassifiercode/g $defFile
sed -i bak -e s/stage_strings/stageStrings/g $defFile
sed -i bak -e s/stage_noshoots/stageNoshoots/g $defFile
sed -i bak -e s/stage_tppoints/stageTppoints/g $defFile
sed -i bak -e s/mod_dl/modDl/g $defFile
sed -i bak -e s/mod_dq/modDq/g $defFile
sed -i bak -e s/mod_dv/modDv/g $defFile
sed -i bak -e s/mod_pf/modPf/g $defFile
sed -i bak -e s/mod_pr/modPr/g $defFile
sed -i bak -e s/mod_sq/modSq/g $defFile
sed -i bak -e s/sh_age/shAge/g $defFile
sed -i bak -e s/sh_cc/shCc/g $defFile
sed -i bak -e s/sh_del/shDel/g $defFile
sed -i bak -e s/sh_dq/shDq/g $defFile
sed -i bak -e s/sh_dvp/shDvp/g $defFile
sed -i bak -e s/sh_eml/shEml/g $defFile
sed -i bak -e s/sh_fn/shFn/g $defFile
sed -i bak -e s/sh_frn/shFrn/g $defFile
sed -i bak -e s/sh_gen/shGen/g $defFile
sed -i bak -e s/sh_grd/shGrd/g $defFile
sed -i bak -e s/sh_id/shId/g $defFile
sed -i bak -e s/sh_law/shLaw/g $defFile
sed -i bak -e s/sh_lge/shLge/g $defFile
sed -i bak -e s/sh_lgp/shLgp/g $defFile
sed -i bak -e s/sh_ln/shLn/g $defFile
sed -i bak -e s/sh_mil/shMil/g $defFile
sed -i bak -e s/sh_mod/shMod/g $defFile
sed -i bak -e s/sh_num/shNum/g $defFile
sed -i bak -e s/sh_pf/shPf/g $defFile
sed -i bak -e s/sh_ph/shPh/g $defFile
sed -i bak -e s/sh_sqd/shSqd/g $defFile
sed -i bak -e s/sh_uid/shUid/g $defFile
sed -i bak -e s/sh_uuid/shUuid/g $defFile
sed -i bak -e s/sh_wlk/shWlk/g $defFile
